### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by anseljh** [kemitchell/smart-quotes.js#1]
I have run into some unexpected behavior with quotation makrs in my forms, so I'm going to add some tests first and then try to run it down.

![2015-10-07-terms-quotes](https://cloud.githubusercontent.com/assets/2075772/10354795/aa9a0cc4-6d18-11e5-925f-389babaf8cc1.png)

Not sure if this is a bug here or in commonform/commonform-docx.

**Comment by kellym** [comment]
You might try the original repo, as there are some tests there: https://github.com/kellym/smartquotesjs/.  Can you post the raw text in a new issue there?
